name: extract_model
channels:
  - conda-forge
dependencies:
  - python>=3.7,<3.10
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - cf_xarray
  - cmocean
  - dask <=2022.05.0 # https://github.com/axiom-data-science/extract_model/issues/49
  - matplotlib
  - netcdf4
  - numpy
  - numba
  - pip
  - requests
  - scikit-learn
  - xarray
  - xcmocean
  - xesmf  # don't install if on windows
  - xoak
  # - pip:  # install from github to get recent PRs I contributed
  #   - git@github.com:xarray-contrib/cf-xarray.git
