name: extract_model
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - cartopy
  - cf_xarray
  - cmocean
  - dask
  - jupyter
  - jupyterlab
  - matplotlib
  - netcdf4
  - numpy
  - pip
  - requests
  - xarray
  - xcmocean
  - xesmf
  # - pip:  # install from github to get recent PRs I contributed
  #   - git@github.com:xarray-contrib/cf-xarray.git
