name: extract_model
channels:
  - conda-forge
dependencies:
  - python=3.8
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - jupyter
  - jupyterlab
  - xarray
  - numpy
  - scipy
  - dask
  - netcdf4
  - pandas
  - matplotlib
  - cf_xarray
  - xcmocean
  - cmocean
  - pip:
    - git+https://github.com/pangeo-data/xESMF.git#egg=xESMF
