name: extract_model
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  # - cf_xarray
  - cmocean
  - dask
  - jupyter
  - jupyterlab
  - matplotlib
  - netcdf4
  - numpy
  - pip
  - requests
  - xarray
  - xcmocean
  - xesmf
  - pip:
      cf_xarray
