name: extract_model
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  # - cf_xarray
  - cmocean
  - dask
  - jupyter
  - jupyterlab
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - xarray
  - xcmocean
  - xesmf
  - pip:
    # use cf-xarray from github to include recent variable naming work
    - git+ssh://git@github.com/xarray-contrib/cf-xarray.git
