name: test_env_extract_model
channels:
  - conda-forge
dependencies:
  - python=3.8
  ############## These will have to be adjusted to your specific project
  - cf_xarray
  - cmocean
  - dask
  - jupyter
  - jupyterlab
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - xarray
  - xesmf
  ##############
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
    - xcmocean
