name: test_env_extract_model
channels:
  - conda-forge
dependencies:
  - python=3.7
  ############## These will have to be adjusted to your specific project
  - cartopy
  - cf_xarray
  - cmocean
  - dask <=2022.05.0 # https://github.com/axiom-data-science/extract_model/issues/49
  - jupyter
  - jupyterlab
  - matplotlib
  - netcdf4
  - numpy
  - pip
  - requests
  - xarray
  - xcmocean
  - xesmf
  ##############
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
