name: test_env_extract_model
channels:
  - conda-forge
dependencies:
  - python=3.7
  ############## These will have to be adjusted to your specific project
  # - cf_xarray
  - cmocean
  - dask
  - jupyter
  - jupyterlab
  - matplotlib
  - netcdf4
  - numpy
  - pip
  - requests
  - xarray
  - xcmocean
  - xesmf
  ##############
  - pytest
  - pip:
    - cf_xarray
    - codecov
    - pytest-cov
    - coverage[toml]
