name: test_env_extract_model
channels:
  - conda-forge
dependencies:
  - python=3.8
  ############## These will have to be adjusted to your specific project
  # - cf_xarray
  - cmocean
  - dask
  - jupyter
  - jupyterlab
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - xarray
  - xcmocean
  - xesmf
  ##############
  - pytest
  - pip:
    # use cf-xarray from github to include recent variable naming work
    - git+ssh://git@github.com/xarray-contrib/cf-xarray.git
    - codecov
    - pytest-cov
    - coverage[toml]
