name: test-env-mac-unix
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cf_xarray
  - cmocean
  - dask <=2022.05.0 # https://github.com/axiom-data-science/extract_model/issues/49
  - matplotlib
  - netcdf4
  - numpy
  - numba
  - pip
  - requests
  - scikit-learn
  - xarray
  - xcmocean
  - xesmf
  - xoak
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
