name: extract_model_docs
channels:
  - conda-forge
dependencies:
   - python=3.8
   # If your docs code examples depend on other packages add them here
   - cf_xarray>=0.6
   - cmocean
   - dask
   - extract_model
   - jupyter
   - jupyterlab
   - matplotlib
   - netcdf4
   - numpy
   - pip
   - pooch
   - requests
   - xarray
   - xcmocean
   - xesmf
   # These are needed for the docs themselves
   - numpydoc
   - sphinx
   - sphinx_rtd_theme
   - ipython
   - nbconvert
   - nbformat
   - ipykernel
   - pandoc
   - recommonmark
   - pip
   - pip:
     - docrep<=0.2.7
     - nbsphinx
     - jupyter_client
     - sphinx_pangeo_theme
     - sphinx-copybutton
     - sphinxcontrib-srclinks
