name: extract_model_docs
channels:
  - conda-forge
dependencies:
   - python=3.8
   # If your docs code examples depend on other packages add them here
   # - cf_xarray
   - cmocean
   - dask
   - extract_model
   - jupyter
   - jupyterlab
   - matplotlib
   - netcdf4
   - numpy
   - pandas
   - pip
   - pooch
   - xarray
   - xcmocean
   - xesmf
   # These are needed for the docs themselves
   - numpydoc
   - sphinx
   - sphinx_rtd_theme
   - ipython
   - nbconvert
   - nbformat
   - ipykernel
   - pandoc
   - recommonmark
   - pip
   - pip:
     # use cf-xarray from github to include recent variable naming work
     - git+git://github.com/xarray-contrib/cf-xarray#egg=cf-xarray
     - docrep<=0.2.7
     - nbsphinx
     - jupyter_client
     - sphinx_pangeo_theme
     - sphinx-copybutton
     - sphinxcontrib-srclinks
