name: extract_model_docs
channels:
  - conda-forge
dependencies:
   - python=3.8
   # If your docs code examples depend on other packages add them here
   - extract_model
   # These are needed for the docs themselves
   - pip
   - pip:
     - docrep<=0.2.7
     - ipython
     - ipykernel
     - jupyter_client
     - nbconvert
     - nbformat
     - nbsphinx
     - numpydoc
     - pandoc
     - recommonmark
     - sphinx_pangeo_theme
     - sphinx-copybutton
     - sphinxcontrib-srclinks
     # https://stackoverflow.com/questions/68642540/nbsphinx-causes-build-to-fail-when-building-jupyter-notebooks
     - sphinx==4.0.2
     - sphinx_rtd_theme
